# -*- coding: utf-8 -*-
"""Flask22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cmCbwNfWnwtaND-RqIjQs81zJNFOi9F
"""

# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('flask2-864fc')
jovian.set_colab_id('14cmCbwNfWnwtaND-RqIjQs81zJNFOi9F')

from flask import Flask

app = Flask(__name__)

@app.route('/')

def home():
    return 'Hi sharath kumar, How are you?'
if __name__ == '__main__':
    app.run(debug=True)